FROM nginx:1.27-alpine
COPY LICENSE NOTICE /usr/share/licenses/stowarr/
COPY src/stowarr/web /usr/share/nginx/html/assets
COPY src/stowarr/web/index.html /usr/share/nginx/html/index.html
COPY docker/nginx.conf.template /etc/nginx/templates/default.conf.template
